version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - python docs/markdown_builder.py --output docs/getdist_docs_combined.md

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

formats: all

sphinx:
  configuration: docs/source/conf.py
