name: Build Mac App

on:
  workflow_dispatch:
  push:
    branches: [ main, master, mac ]
    paths:
      - 'getdist/gui/**'
      - 'scripts/build_mac_app.py'
      - 'scripts/build_mac_app.sh'
      - '.github/workflows/build_mac_app.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'getdist/gui/**'
      - 'scripts/build_mac_app.py'
      - 'scripts/build_mac_app.sh'
      - '.github/workflows/build_mac_app.yml'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        # Verify uv installation
        source "$HOME/.cargo/env"
        uv --version

    - name: Build Mac App
      run: |
        # Make the script executable
        chmod +x scripts/build_mac_app.sh
        # Show environment info
        echo "Python version:"
        python --version
        echo "uv version:"
        uv --version
        echo "Working directory:"
        pwd
        # Run the build script with verbose output
        ./scripts/build_mac_app.sh

    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: GetDist-GUI-DMG
        path: dist/GetDist-GUI.dmg

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/GetDist-GUI.dmg
        draft: true
        prerelease: false
