name: Build Mac App

on:
  workflow_dispatch:
    inputs:
      skip_signing:
        description: 'Skip signing and notarization (for testing only)'
        required: false
        default: false
        type: boolean
  push:
    branches: [ main, master, mac ]
    paths:
      - 'getdist/gui/**'
      - 'scripts/build_mac_app.py'
      - 'scripts/build_mac_app.sh'
      - '.github/workflows/build_mac_app.yml'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        # Verify uv installation
        source "$HOME/.cargo/env"
        uv --version

    - name: Build Mac App
      run: |
        # Make the script executable
        chmod +x scripts/build_mac_app.sh
        # Show environment info
        echo "Python version:"
        python --version
        echo "uv version:"
        uv --version
        echo "Working directory:"
        pwd
        # Run the build script with verbose output
        ./scripts/build_mac_app.sh

    - name: Import Code Signing Certificate
      if: github.event.inputs.skip_signing != 'true'
      env:
        CERTIFICATE_BASE64: ${{ secrets.MACOS_CERTIFICATE }}
        CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # Create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        # Import certificate from secrets
        echo -n "$CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

        # Create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

        # Import certificate to keychain
        security import $CERTIFICATE_PATH -P "$CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

    - name: Sign Mac App
      if: github.event.inputs.skip_signing != 'true'
      env:
        TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: |
        # Sign the app bundle
        echo "Signing app bundle..."
        codesign --deep --force --verify --verbose --sign "Developer ID Application: $TEAM_ID" "dist/GetDist GUI.app"

        # Verify signature
        echo "Verifying app signature..."
        codesign --verify --verbose "dist/GetDist GUI.app"

    - name: Notarize Mac App
      if: github.event.inputs.skip_signing != 'true'
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_APP_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
        TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: |
        # Create a ZIP archive for notarization
        echo "Creating ZIP archive for notarization..."
        ditto -c -k --keepParent "dist/GetDist GUI.app" "dist/GetDistGUI.zip"

        # Submit for notarization
        echo "Submitting app for notarization..."
        xcrun notarytool submit "dist/GetDistGUI.zip" --apple-id "$APPLE_ID" --password "$APPLE_APP_PASSWORD" --team-id "$TEAM_ID" --wait

        # Staple the notarization ticket
        echo "Stapling notarization ticket to app..."
        xcrun stapler staple "dist/GetDist GUI.app"

        # Create a new DMG with the signed and notarized app
        echo "Creating signed DMG..."
        # Create a temporary directory for the DMG contents
        mkdir -p "dist/dmg"
        # Copy the signed and notarized app bundle to the temporary directory
        cp -r "dist/GetDist GUI.app" "dist/dmg/"
        # Create a symlink to the Applications folder
        ln -s /Applications "dist/dmg/"
        # Create the DMG
        hdiutil create -volname "GetDist GUI" -srcfolder "dist/dmg" -ov -format UDZO "dist/GetDist-GUI-Signed.dmg"
        # Sign the DMG
        codesign --sign "Developer ID Application: $TEAM_ID" "dist/GetDist-GUI-Signed.dmg"
        # Replace the original DMG with the signed one
        mv "dist/GetDist-GUI-Signed.dmg" "dist/GetDist-GUI.dmg"
        # Clean up
        rm -rf "dist/dmg" "dist/GetDistGUI.zip"

    - name: Verify Signed App
      if: github.event.inputs.skip_signing != 'true'
      run: |
        echo "Verifying app signature and notarization..."
        spctl --assess --verbose=4 "dist/GetDist GUI.app"
        echo "Verifying DMG signature..."
        codesign --verify --verbose "dist/GetDist-GUI.dmg"

    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: GetDist-GUI-DMG
        path: dist/GetDist-GUI.dmg

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/GetDist-GUI.dmg
        draft: true
        prerelease: false
