name: tests

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: "Latest Python 3.x"
          os: ubuntu-latest
          python-version: 3.x
        - name: "OS X Python 3.9"
          os: macos-latest
          python-version: 3.9
        - name: "Windows Python 3.11"
          os: windows-latest
          python-version: 3.11

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: flake8 Lint
      if: matrix.os == 'ubuntu-latest'
      uses: py-actions/flake8@v2
      with:
          args: --select=E713,E704,E703,E714,E10,E11,E20,E22,E23,E25,E27,E301,E302,E304,E9,F405,F406,F5,F6,F7,F8,W1,W2,W3,W6 --show-source --statistics
          path: getdist
          max-line-length: "120"

    - name: Install dependencies
      run: |
        python --version
        pip install . 
        git clone --depth=1 https://github.com/cmbant/getdist_testchains

    - name: Run tests
      run: |
        getdist --help
        python -m unittest getdist.tests.getdist_test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.repository_owner == 'cmbant' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -U build twine

    - name: Build package
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1

